GET https://anime-facts-rest-api.herokuapp.com/api/v1/dragon_ball

###
GET https://api.waifu.pics/sfw/waifu

###
Get https://api.genshin.dev/consumables/food

###
GET https://www.gamerpower.com/api/giveaways?platform=pc

###
GET https://animechan.vercel.app/api/quotes/character?name=asuna

###
GET http://localhost:3001/combat/?category=swords
###
GET http://localhost:3001/tools/?_sort=durability&_order=asc